name: CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install all dependencies
        run: npm install

      - name: Run prettier check
        run: npm run prettier

  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install all dependencies
        run: npm install

      - name: Run ESLint check
        run: npm run eslint

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install all dependencies
        run: npm install

      - name: Build static resources
        run: npm run build
